name: EpgGrabber

on:
  schedule:
    - cron: '30 0,12 * * *'

  pull_request:
    branches: [ main ]

  workflow_dispatch:
jobs:

  runCode:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Grab EPG
        run: python .github/xml_split.py epg_CN.xml
